### ISSUE TITLE
arg::Path<'a> does not implement arg::Get<'a>

### ISSUE THREAD

**Issue by brain0** [diwic/dbus-rs#124]
I realized while trying to extract arguments that you can only get an owned Path<'static> from a message, not a Path<'a>. This is very unintuitive and is not usually done this way in Rust. In general a trait like Get<'a> that depends on the lifetime of the message should not implicitly clone strings, Vectors and others.

If anyone actually needs a Path<'static>, they can extract a Path<'a> and call into_static() on it.

**Comment by diwic** [comment]
I agree this is unfortunate, but I could not find a good way around it. I chose ergonomics instead of performance here. Calling into_static might work in simple cases, but not in more complicated cases like this (taken from `stdintf.rs`):

        let objects: ::std::collections::HashMap<::Path<'static>, ::std::collections::HashMap<String, ::std::collections::HashMap<String, arg::Variant<Box<arg::RefArg>>>>> = try!(i.read());

...and you can't have implementations for *both* `Path<'a>` and `Path<'static>` because they would conflict. I guess having different Path structs (like `CStr` and `CString` etc) could work, but not sure it's worth the effort, especially as that would be a breaking change.

**Comment by diwic** [comment]
Not happy about it, but I think this one's going to be a wontfix for reasons stated above.
