### ISSUE TITLE
RefArg: Arrays of arrays are appended as structs

### ISSUE THREAD

**Issue by pinkisemils** [diwic/dbus-rs#151]
As I'm trying to interface with NetworkManager to set DNS servers for a specific network interface, I've come across an issue where `AppendIter.append()` panics when I try to append a non-empty `HashMap<String, HashMap<String, Variant<Box<RefArg>>>>` which is actually constructed by NetworkManager. 
In essence, I'm trying to call `Reapply` with the output of `GetAppliedConnection` on the `org.freedesktop.NetworkManager.Device` interface on a valid object path.
https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Device.html
Example code can be found [here](https://github.com/pinkisemils/dbus-nm-fail), to run it, one must be able to access NetworkManager's DBus interface.
The panic message is as follows
>thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Struct has no fields"', libcore/result.rs:1009:5

**Comment by diwic** [comment]
Thanks, I can reproduce it here. 

The problem is an Array of Arrays somewhere inside a `Box<RefArg>`. The bug is that when retrieved, this part is being stored as a `Vec<Box<RefArg>>`, even if it were more logical to store as a `Vec<Vec<something>>`. We can't do the latter, because it would lead to type explosion (or at least so I assume). 
However, `Vec<Box<RefArg>>` is the representation of a struct when appended. And then the array of array was empty, and empty structs are not allowed.

In general I think it's rare to get a `Box<RefArg>` from someplace and then append it somewhere else, which is why this bug has not been discovered before.

**Comment by pinkisemils** [comment]
Regarding the rarity/validity of the issue, NM people think that this is _the_ way to make ad-hoc adjustments to an interface over DBus. It is a shame that the config is stored as an opaque map of maps. 

Is there a way to code around this? Would having a `HashMap<String, Dict<_>>` resolve this? That doesn't work because `RefArg` doesn't have to be `Clone`'able, but maybe I can make that work.
