### ISSUE TITLE
Please run cargo-fmt

### ISSUE THREAD

**Issue by a1ien** [diwic/dbus-rs#191]
You have many line with mixing tab and space formatting. And also very long lines.
`cargo-fmt` fix all problems.

**Comment by diwic** [comment]
I changed the tabs to spaces. 

One of the reasons I don't use `cargo-fmt` is the way it breaks lines (it does that too often), making the code less readable, as less code fits on the screen so you have to scroll up and down a lot.

**Comment by diwic** [comment]
I gave it another try, but `rustfmt` is still not good enough. Filed bug https://github.com/rust-lang/rustfmt/issues/3699

**Comment by a1ien** [comment]
But you still have too long lines. For example github web have around 132 width line. And scroll screen to right need more action then scroll up and down.
For example 
https://github.com/diwic/dbus-rs/blob/a13969899e38795d7cc41b199a70ced6a77cb3c7/dbus/src/ffidisp/connection.rs#L544
https://github.com/diwic/dbus-rs/blob/a13969899e38795d7cc41b199a70ced6a77cb3c7/dbus/src/ffidisp/connection.rs#L544

Why you think long if it's cool?

About you "bug" in rustfmt. It's have different behavior because these are different constructions.
1) It's simple `if` and it's must split on two line.
2) it's something like ternary `if` in c++.

**Comment by diwic** [comment]
> Why do you think that if in one line is cool?

I haven't said that. In that particular case I don't mind much if it is on one line or three.

 > About you "bug" in rustfmt. It's have different behavior because these are different constructions.

This statement is either wrong, or I have failed to understand you.

Anyway, I strongly believe enhancing the code to fix bugs and have more features, is more important than strictly adhering to a certain line length.

**Comment by timbodeit** [comment]
I very much agree with @a1ien on the point that this project should be rustfmted.

Inconsistent style slows developers down. Thinking about the git diff implications of whitespace changes takes time. Having to look at surrounding code to match its style when making a tiny change takes time. Reading code in a file that is in itself inconsistent takes longer, than reading code that is written in a consistent style.

I don't want to start an argument about style preferences. It is your project and if you want to impose a style guide that differs from the rustfmt, I have to accept that. Either way I'll be grateful for what you have put out for everyone to use.

But I do very strongly urge you to define and use some type of automated format. The best part about it is, that if we automate format, we don't have to argue about what format exactly to use.
I can run rustfmt with the options that make me the most productive before I start working on a change. And when committing and filing a pull request, I simply format it again with the configuration that you as the project owner prefer.

By not using rustfmt at all, you are taking that option from me. Therefore I strongly urge you to once again think about, whether slight differences in code representation are more important to you than code consistency and productivity of external contributors. If the answer to that question is no, please start using rustfmt now, with whatever configuration you deem to be best, instead of waiting for the time when rustfmt will be perfect.

**Comment by davidgraeff** [comment]
Personally I have enabled auto formatting in my IDE (CLion) to keep the diff on point for every single commit. Whitespace-changes noise is really annoying. I agree though that the rustfmt defaults are very "traditional". My personal `rustfmt.toml` looks like this:

```toml
match_block_trailing_comma = true
use_try_shorthand = true
use_field_init_shorthand = true
max_width = 120
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = true
```

**Comment by diwic** [comment]
@timbodeit 
Some people will only contribute to projects that enforce rustfmt, others will only contribute to projects that don't, but most will accept either. Whether rustfmt or not rustfmt is more productive depends on who you ask, so please don't state that rustfmt increases productivity like it was always true, because it is not.

The user "kornel" makes a few comments [in this thread](
https://users.rust-lang.org/t/how-are-you-using-rustfmt-and-clippy/31082/57) about why rustfmt decreases productivity; I sympathize with his arguments.

**Comment by timbodeit** [comment]
@diwic I'm not trying to state that `rustfmt` increases everyone's productivity. I'm saying that consistent formatting does. Is the idea that code format within a project should be as consistent as possible without costing unreasonable amounts of developer time, something that you could get behind?

I do sympathize with kornels arguments about how gofmt performs better than rustfmt. Preserving consciously placed newlines, structuring by semantic importance instead of syntactical length, and running rustfmt occasionally and applying only those changes that don't make readability worse are things that I can get behind. My sympathy goes so far, that I support the [suggestion by TomP](https://users.rust-lang.org/t/how-are-you-using-rustfmt-and-clippy/31082/13) to make rustfmt adopt this behavior when an optional flag is set. While this would be better than the rustfmt we have today, I still believe that using rustfmt is better, than using no formatter at all. But as you're rightfully saying, this view is personal preference and not objective truth applying to everyone.

> Therefore I strongly urge you to once again think about, whether slight differences in code representation are more important to you than code consistency and productivity of external contributors.

I did honestly mean the above statement as an open question. If your answer to that question is "yes, these slight differences are what makes me (and possibly other people that for example know the codebase as well as I do) significantly more productive and this makes it worth to reduce the productivity of some external contributors" then I'm not going to argue with that conscious decision.

In any case, thank you for your explanation. Either way, this thread makes the reasoning behind your decision more understandable.

> Some people will only contribute to projects that enforce rustfmt, others will only contribute to projects that don't, but most will accept either. Whether rustfmt or not rustfmt is more productive depends on who you ask

I wouldn't hold back contributions over the politics of whether someone enforces rustfmt in the CI or not. For small changes, I don't really care. For major changes, I'll run rustfmt where I feel like the original format doesn't offer me the same productivity. In the end it's the project owners decision if he wants my end-result in his codebase or not.

**Comment by diwic** [comment]
@timbodeit 
So it's a combo of 1) I have not found a way to configure `rustfmt` so that it does not do things that annoy me (it does not make the code unreadable per se, but it splits it over lines so that I have to scroll more than otherwise), 2) it slows me down because it's one more thing to remember, and 3) the important coding style rules (like "variables are snake_case") are already in the compiler, so the style is consistent enough even without `rustfmt`.

Slight inconsistencies in code formatting does not annoy me and does not decrease my productivity. (Really bad code formatting does, but IIRC that has only happened once during four years of dbus-rs.)

That said; should anyone want to do **lots** of contributions, almost at co-maintainer level, then that person's personal preference would have a lot of weight as well.

**Comment by hellow554** [comment]
So after 2,5 years this is still an issue for you? 

`rustfmt` may not be the style *you* like, but the community™ has agreed on.
TBH the code style currently is a little mess. It's not consistent nor it is very readable in some places.

So I ask you again. Reenable rustfmt, use the default settings (maybe adjust the max line length if at all) and reformat the whole project.

**Comment by diwic** [comment]
@hellow554 The coding style needs to fit the people reading and writing the code, the one(s) that takes responsibility to fix bugs as they come up. Not the people standing by. 

That said, there is also #244 to take into account here. So, are you (or anyone else) interested in maintaining this crate, but see rustfmt as the only blocker for doing so? Then let me know, and then fork it with such an intention. Run rustfmt, then e g finish the native implementation. Continue to make improvements to your fork over the course over maybe half a year so I know that you're reliable. If you make this project thrive again, I'll hand it over to you. Does that make sense?

**Comment by hellow554** [comment]
Sure enough. But you don't know who's reading your code. You know that (currently) only you are writing this code. That's a point.

You say that you are seeking for volunteers that want to contribute to your crate, which is perfectly fine. I can understand that, that maintaining a crate is a very cumbersome task and I really appreciate your work here.  
It has a very good documentation, tests and a good thought-out coding baseline. Thumbs up for that.

I'm currently running clippy on your code and fix the issues that pop up. While browsing throught that I mark code positions that I want to examine further, because you either tried to reinvent the wheel (https://github.com/diwic/dbus-rs/blob/9d8846a75fe78217ba46be27f2843d26cff276a7/dbus-strings/src/validity.rs#L1-L6 or https://github.com/diwic/dbus-rs/blob which can be replaced by [`is_ascii_alphabetic`](https://doc.rust-lang.org/std/primitive.u8.html#method.is_ascii_alphabetic) or /9d8846a75fe78217ba46be27f2843d26cff276a7/dbus-native-channel/src/address.rs#L3-L10) which is [`option_env!`](https://doc.rust-lang.org/std/macro.option_env.html)

So I do what you said. I do what I think is the best and make a pull request. Let's see how it works :)
