### ISSUE TITLE
The async story

### ISSUE THREAD

**Issue by davidgraeff** [diwic/dbus-rs#218]
I'm a little bit puzzled on the direction towards a non blocking / async approach. I quickly summarize what I have understood so far by reading through some sources.

* The `dbus` crate should stay "futures" / "async runtime"-dependency free. Thanks to rusts 1.38(?) `std::future` and support in the *nonblock* API, that API can be already used with async/await however.

* The `dbus-futures` crate is a proof of concept, I guess? It dates back to the dbus crates 0.6 time and if adapted to the current ecosystem and newest versions, the crate potentially slims down a fairly bit. The crate offers support for an "exotic" runtime / executor ("tml") and the old tokio 0.1 runtime. It concentrates on the client side and provides a "connection" type and two (future library 0.3 based) stream types for responses and signal-watching respectively.

* The `dbus-tokio` crate offers support for the old tokio 0.1 and new tokio 0.2 runtime. It targets the client and server side. The server side is based on the old future library 0.1 with the non-standard `Future` trait. For the client side it offers a very useful "connection" type that abstracts over the `nonblock` **LocalConnection** and **SyncConnection**.

To be honest, I'm mostly interested in the client part, but I guess, defined directions and patterns will apply to both client and server parts anyway.

There are two issues to discuss that I can think of. Modeling the non blocking API in an idiomatic async rust-ish way and interacting with the executor (handling over the socket file descriptors).

### Modeling the API, Discussion

The rust async ecosystem is unfortunately no entirely sound right now. For dbus signal watching and a convenient API, a *Stream* type is probably the most idiomatic API right now. Such a type hasn't made it into the standard library yet. Judging by https://github.com/rust-lang/rfcs/blob/master/text/2394-async_await.md#generators-and-streams it might however turn out that the language will have generators even before streams or never have a standard stream type ever.

For now I assume that we want to have the Stream based API. Both tokio 0.2 and futures 0.3 (as well as many more crates) offer a stream type, but they also define a few types slightly different from each other (AsyncRead/AsyncWrite). I like the idea of settling on the `futures_util` (futures 0.3) crate.

I propose to add Stream based APIs for dbus signals to the `dbus` crates non blocking API (hidden behind a feature flag?). For the client side you find a naive Stream implementation below.

<details>
  <summary>Code</summary>

```rust

#[derive(Default)]
struct SignalStreamState {
    signal_queue: VecDeque<dbus::Message>,
    waker: Option<Waker>,
    done: bool,
}


pub struct SignalStream<T> {
    connection: Arc<SyncConnection>,
    match_str: String,
    rule_handler: u32,
    state: Arc<Mutex<SignalStreamState>>,
    _data: PhantomData<T>,
}

/// The stream implementation. The futures+tokio crate have settled on a "poll_next" method.
impl<T: SignalArgs + 'static> Stream for SignalStream<T>
    where T: dbus::arg::ReadAll {
    type Item = (T, String);
    fn poll_next(self: Pin<&mut Self>, ctx: &mut task::Context) -> task::Poll<Option<Self::Item>> {
        let mut state = self.state.lock().unwrap();

        if let Some(message) = state.signal_queue.pop_back() {
            let v = T::from_message(&message).unwrap();
            return task::Poll::Ready(Some((v, message.path().and_then(|f| Some(f.to_string())).unwrap_or_default())));
        }
        if state.done {
            return task::Poll::Ready(None);
        }
        state.waker = Some(ctx.waker().clone());
        task::Poll::Pending
    }
}

impl<T: SignalArgs + 'static> SignalStream<T> {
    pub async fn new(connection: Arc<SyncConnection>, mr: MatchRule<'static>) -> Result<Self, Error> {
        let match_str = mr.match_str();

        let p = dbus::nonblock::Proxy::new("org.freedesktop.DBus", "/", connection.clone());
        // Based on PR 217's (+follow up) additional generated code for dbus::nonblock::stdintf
        use dbus::nonblock::stdintf::org_freedesktop_dbus::DBus;
        p.add_match(&match_str).await?;

        let state = Arc::new(Mutex::new(SignalStreamState { ..Default::default() }));
        let state_clone = state.clone();
        let rule_handler = connection.start_receive(
            mr,
            Box::new(move |h: dbus::Message, _| {
                let mut state = state_clone.lock().unwrap();
                state.signal_queue.push_front(h);
                if let Some(waker) = state.waker.take() {
                    waker.wake();
                }
                true
            }),
        );

        Ok(SignalStream { connection, match_str, rule_handler, state, _data: Default::default() })
    }
}

/// Remove the receive dispatcher rule and then ask the dbus daemon to no longer send us messages
/// of this match_rule.
impl<T> Drop for SignalStream<T> {
    fn drop(&mut self) {
        self.connection.stop_receive(self.rule_handler);
        self.rule_handler = 0;
        {
            let mut state = self.state.lock().unwrap();
            state.done = true;
        }
        let match_str = self.match_str.clone();
        let connection = self.connection.clone();
        // This is where I'm struggling. Drop is not async aware.
        // It is no problem to spawn the remove_match task to an executor here.
        // But it ties the implementation to an executor at the same time.
        // The connections internal process queue can maybe exploited instead, so that
        // the `start_receive` callback from above gets a specific quit message.
        spawn(async move {
            let p = dbus::nonblock::Proxy::new("org.freedesktop.DBus", "/", connection);
            use dbus::nonblock::stdintf::org_freedesktop_dbus::DBus;
            let _ = p.remove_match(&match_str).await;
        });
    }
}
```

Usage:

```rust
    pub async fn print_access_point_changes(&self) -> Result<(), CaptivePortalError> {
        use dbus_tokio::SignalStream;

        use access_point::OrgFreedesktopNetworkManagerAccessPointPropertiesChanged as APChanged;
        let rule = APChanged::match_rule(None, None).static_clone();
        let mut stream: SignalStream<APChanged> = SignalStream::new(self.conn.clone(), rule).await?;
        pin_utils::pin_mut!(stream);
        while let Some((value, path)) = stream.next().await {
            println!("Access point changed properties: {:?} on {}", value.properties, path);
        }
        Ok(())
    }
```

dbus-codegen could generate factory methods for each encountered signal, to retrieve readily setup `SignalStream`s. A `Proxy` would then have methods like `proxy.watch_whatever_signal_name() -> SignalStream`.

</details>

### Interacting with the executor

I respect that the `dbus` crate doesn't want to settle on an executor, so complementary crates for different executors are necessary. The connection type of the  dbus-tokio crate is what I imagine such a crate should offer.

For my own needs of an async/await aware dbus client API, I have used the connection part of dbus-tokio and the above `SignalStream` struct, which is about 150 LOC. And only 7 lines of the connection part are tokio specific, the rest can potentially be shared amongst different runtimes.

For the server side you need a second stream type for incoming requests, another 100 LOC maybe, with probably a few executor specific lines as well. But I really do wonder what all the other files of dbus-futures and dbus-tokio do and if that is still necessary?

Have I missed something, any further thoughts? I'd be happy for a discussion.

**Comment by diwic** [comment]
Thanks for the interest!

If we take the dependency / crate division question first. There is more than one way to go here, and I'm open for input, because I'm not completely sure myself.

 * Some crate needs to depend on Tokio
 * Some crate needs probably depend on Futures (if we want streams)

We could have:

 1) dbus (dependency free) + dbus-futures (depends on futures + feature flags for tokio or tml) or
 2) dbus (feature flag for futures) + dbus-tokio / dbus-tml 
 3) or even dbus (dependency free) + dbus-futures (depends on futures) + dbus-tokio / dbus-tml

As you say the state of async ecosystem is in flux right now with the new stuff called "preview" or "alpha", so it's not easy to know where things will end up. As for executors, we have tokio, async-std and tml, where async-std [does not support listening on custom fds](https://github.com/async-rs/async-std/issues/60) and [tml](https://crates.io/crates/thin_main_loop) was something I wrote because I figured it would be a good building block over OS abstractions, but so far it has failed to gain tracktion.

**Comment by diwic** [comment]
As for Streams, I'm not sure. I tried it first, because I too thought this would make the most ergonomic API. But it was pointed out to me [here](https://www.reddit.com/r/rust/comments/cz6te1/async_preventing_reordering_of_streams_and_futures/) that if streams are the main/primary way to listen to incoming messages, it's hard to prevent reordering of messages. So there are important use cases that streams can't handle.

In that light, the question is what we actually need the `futures` crate for. Will it be just for streams or are there many other things you envision where the `futures` crate be helpful or even essential?

**Comment by diwic** [comment]
> The dbus-futures crate is a proof of concept, I guess?

I guess so too...consider it abandoned at this point. I might still copy-paste some code from it though, so I haven't deleted the code.

 > The dbus-tokio crate offers support for the old tokio 0.1 and new tokio 0.2 runtime. It targets the client and server side. The server side is based on the old future library 0.1 with the non-standard Future trait. For the client side it offers a very useful "connection" type that abstracts over the nonblock LocalConnection and SyncConnection.

Once tokio is at stable 0.2, I'm planning to delete the 0.1 part, having a 0.2 dependency only. The connection components are the only things that are going to be there - both clients and servers need connections 🙂. As for the async server part, that's something I want to support with [crossroads](https://github.com/diwic/dbus-rs/tree/master/dbus/src/crossroads), the successor to `tree`, which I'm currently working on.

**Comment by davidgraeff** [comment]
I noticed that the current dbus-tokio io-resource task does not always wake up if messages have to be flushed.

And looking at the code I did not find any hint on where the task is notified about new data in the libdbus outgoing queue.

#### Status Quo

Quick summarize on how it works right now (to my understanding which might be wrong):

There is a `Sender` trait with a `send(message)` method and a `BlockingSender`/`NonblockReply` trait. For a non-block message the code flow looks like one of the following:

* `Sync/LocalConnection::send` via `Sender::send` --> Channel::Send --> ffi::dbus_connection_send
* `Sync/LocalConnection::send_with_reply` via `NonblockReply::send_with_reply` --> Channel::send --> ffi::dbus_connection_send
 
Assuming that `ffi::dbus_connection_send` will only queue a message but is not interacting with the dbus socket, the IOResource tasks is never notified.

#### Using the task contexts watcher

I think a call to the IOResource tasks `Watch`er on a send is missing. Although convenient it cannot be done in `Channel::send`. Instead this would be added to `Sender::send` and `NonblockReply::send_with_reply`:

Changes to LocalConnection/SyncConnection in `nonblock.rs`:
```rust
pub struct SyncConnection {
    waker: Mutex<Option<Waker>>,
    ...
}
pub struct LocalConnection {
    waker: RefCell<Option<Waker>>,
    ...
}
```

Changes to Sender/NonblockReply impl in `nonblock.rs` (only shown for `Sender`):
```rust
impl Sender for LocalConnection {
    fn send(&self, msg: Message) -> Result<u32, ()> {
        let r = self.channel.send(msg);
        if let Some(v) = self.waker.borrow_mut().take() {
            v.wake();
        }
        r
    }
}
impl Sender for SyncConnection {
    fn send(&self, msg: Message) -> Result<u32, ()> {
        let r = self.channel.send(msg);
        // try_lock: It doesn't matter if this method or a concurrent call schedules a wakeup
        if let Ok(mut v) = self.waker.try_lock() {
            if let Some(v) = v.take() {
                v.wake();
            }
        }
        r
    }
}
```

And the dbus tokio Resource IO `poll_internal` would be changed to be similar to:

```rust
impl<C: AsRef<Channel> + Process> IOResource<C> {
    fn poll_internal(&self, ctx: &mut task::Context<'_>) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        // Set the waker 
        self.connection.set_waker(ctx.waker().clone());

        let c: &Channel = (*self.connection).as_ref();
        self.registration.register(&mio::unix::EventedFd(&c.watch().fd))?;

        // Always flush when this task got scheduled. It might have been scheduled by the waker.
        c.flush();

        while let Poll::Ready(v) = r.poll_read_ready(ctx)? {
            c.read_write(Some(std::time::Duration(0))).map_err(|_| Error::new_failed("Read/write failed"))?;
            self.connection.process_all();
        }
}
```

Maybe I'm missing a piece here and libdbus does notify the socket.

#### Timeouts

What the non-blocking part requires though to be on par with the blocking implementation is a timeout mechanism. Either per message or a global one.

If a `Message` itself doesn't store a timestamp (haven't looked into the code), the replies hashmap of `LocalConnection`/`SyncConnection` would need to store one.

**Comment by diwic** [comment]
Indeed this new stuff is not battle tested, it's just up and running.

 > Assuming that ffi::dbus_connection_send will only queue a message but is not interacting with the dbus socket, the IOResource task is never scheduled to flush the queue.

I looked it up: https://dbus.freedesktop.org/doc/api/html/dbus-connection_8c_source.html
`dbus_connection_send` makes an attempt to actually send the message. 

What is missing is tests for what happens when buffers are full, like if you're sending/receiving a really big message, or maybe a few medium sized messages that together adds up to something larger than some libdbus limit, to verify that it is something that works correctly. 

 > What the non-blocking part requires though to be on par with the blocking implementation is a timeout mechanism.

Agreed. Unfortunately, timeouts and timers in general seems to be an executor specific thing. The `futures` crate has nothing about timeouts, it's done within [tokio](https://docs.rs/tokio/0.2.0-alpha.6/tokio/future/trait.FutureExt.html). So it's something I haven't looked into and figured out how to best solve. In the mean time, using the `FutureExt` trait from `tokio` seems to be the easiest way to add a timeout to a method call (or similar).

**Comment by davidgraeff** [comment]
> I looked it up: https://dbus.freedesktop.org/doc/api/html/dbus-connection_8c_source.html
dbus_connection_send makes an attempt to actually send the message.

Thanks for looking this up. I came to the same conclusion.

That explains why it works sometimes. Sending is not the problem. I should have mentioned that. IOResource does not always wake up for the reply. Without timeouts that means a nonblock application will hang at some point.

Might be a race condition, `ffi::dbus_connection_send` lives in the main thread and `IOResource` in another (at least in my code where I'm using tokio spawn on the default executor). 

> using the FutureExt trait from tokio

Yes, `FutureExt` offers a nice API. On a timeout some clean ups have to happen in the connection though (removing expected replies etc). Are you in favour of a per-connection timeout or per message timeout?

* A per-connection timeout would remove all outstanding replies of a connection when n seconds passed without an incoming message.
* Per-message would require a timestamp embedded in a message (I don't know if that's already the case) and a few techniques to not iterate over all messages each time, to find expired ones.

**Comment by diwic** [comment]
> IOResource does not always wake up for the reply.

Then that is what you should debug further. Like, what does `channel.watch()` return under different circumstances?
Probably we should wake up the main loop in case `channel.watch()` increases (i e we watch for more things), but I prefer not to do that from the libdbus toggle watch callback because that would not be panic safe.

 > Per-message would require a timestamp embedded in a message (I don't know if that's already the case) and a few techniques to not iterate over all messages each time, to find expired ones.

Or maybe consider calling `cancel_reply` if a `MethodReply` is dropped?

**Comment by diwic** [comment]
> Might be a race condition

I tried changing a few things around in https://github.com/diwic/dbus-rs/commit/e2c9d915ce9c846369089379c852999e960c0702 - can you see if that helps? If not, please make a debug print inside `toggled_watch_cb` (in `channel.rs`) to help us troubleshoot why it does not wake up.

**Comment by diwic** [comment]
As for timeouts, maybe it could work like this:

`NonblockReply` gets two additional methods, one `fn set_timeout_handler(&mut self, handler: Box<Fn(u32, Duration) + Send + Sync + 'static>)` and one `fn timeout_happened(&self, u32)`. (Possibly these will return results if appropriate.)

`dbus-tokio` calls `set_timeout_handler` at startup and implements the timeout handler, i e, whenever the handler is called, it spawns a future that waits for `duration` and then calls `timeout_happened`. This method will check if the method reply is still there, and if so report a timeout error to the `MethodReply`. 

Possibly, the timeout handler can return a token which can be dropped by the connection in case it is no longer interested in the timeout (i e, if the method has been properly replied to by the other peer).

**Comment by diwic** [comment]
Okay, so I finally had some time to work on this yesterday. As a result:

 1. `dbus` crate now has a `futures` feature flag, and the entire `nonblock` module is behind it
 2. Timeouts are supported. This turned out to be more complex (and require some more boxing) than anticipated, but at least it works now.
 3. As for the `SignalStream` functionality, it's something I should add, but it seems to be possible to do in a backwards compatible fashion, so I could possibly release a first version without it.

@davidgraeff  How does that sound?

**Comment by diwic** [comment]
I have now released dbus 0.8.0 and dbus-tokio 0.5.0.

**Comment by diwic** [comment]
@davidgraeff 

Ok, so I had a look at your `SignalStream`, and here's my thoughts on matching incoming signals.

An API user might want to do:

 1. Something synchronously for every matching message
 2. Something asynchronously for every matching message
 3. Use the `Stream` API to iterate over every matching message

I'm opting for nr 1. (sync cb) at this point, because:

 * It is the most performant given the current implementation
 * One can make a callback that does 2. (async cb) or 3. (stream api) without much difficulty
 * It always processes the messages in incoming order (no reordering issues)

An async cb will have to do a `tokio::spawn` inside the cb, for the async part of the cb.

As for the `Stream` API, `futures::channel::mpsc` contains an implementation of this, so we don't have to make our own channel-like struct (like your `SignalStream`). Given a callback API, one can just create a channel from the `futures` crate, move the channel's sender into the cb, and send the message from the cb, the `ReadAll` arguments, or something else.
Also, reading up on this, I see there is also the issue of backpressure and at this point and I'm not sure how to best handle that, so better leave it to the API user.

**Comment by davidgraeff** [comment]
> so better leave it to the API user.

The Rust community hasn't decided on a Stream type yet anyway. But I'd say at least an example on how to consume dbus signal events via async means might be beneficial.

> As for the Stream API, futures::channel::mpsc contains an implementation of this

True. IMO a wrapper type with a custom Drop implementation is necessary though to unregister interest in given dbus signal events.

**Comment by diwic** [comment]
@davidgraeff Unfortunately calling the dbus server to unregister interest is an async call, and destructors cannot be async. Anyhow this is what I came up with: https://docs.rs/dbus/0.8.1/dbus/nonblock/struct.MsgMatch.html
