### ISSUE TITLE
Error when calling `tree.start_receive(&connection)`

### ISSUE THREAD

**Issue by nikonthethird** [diwic/dbus-rs#227]
I am currently updating to `dbus` 0.8. There is one remaining error that I cannot get fixed. The error message is:

```text
pub fn start_receive<C>(self, connection: &C)
where C: channel::MatchingReceiver<F=Box<dyn FnMut(Message, &C) -> bool>> + channel::Sender
Connects a Connection with a Tree so that incoming method calls are handled.

type mismatch resolving `<dbus::blocking::Connection as dbus::channel::MatchingReceiver>::F == std::boxed::Box<(dyn for<'r> std::ops::FnMut(dbus::message::Message, &'r dbus::blocking::Connection) -> bool + 'static)>`
expected type `std::boxed::Box<(dyn for<'r> std::ops::FnMut(dbus::message::Message, &'r dbus::blocking::Connection) -> bool + std::marker::Send + 'static)>`
   found type `std::boxed::Box<(dyn for<'r> std::ops::FnMut(dbus::message::Message, &'r dbus::blocking::Connection) -> bool + 'static)>`rustc(E0271)
```

This is the offending line:

```rust
tree.start_receive(&connection);
```

`tree` is of type `dbus::tree::Tree`, and `connection` of type `dbus::blocking::Connection`.

As far as I can tell, [`connection` impls `MatchingReceiver` with `Send`](https://docs.rs/dbus/0.8.0/src/dbus/blocking.rs.html#173), so this should work without change, right?

I don't unterstand why the error message says `std::marker::Send` is missing.

**Comment by diwic** [comment]
Okay, after some experiments I was able to make `start_receive_send` and `start_receive_sync` methods for `Connection` and `SyncConnection` as well.

Because `Connection` can be sent between threads, the tree itself must also be `Send`. Only `MTSync` trees are sendable, so either switch to `LocalConnection` or `MTSync` if you have this problem.

Please try it and let me know if it works for you.

**Comment by nikonthethird** [comment]
Thank you for the quick reply. I just tested, it, the problem persists. The type of my tree is:

```rust
dbus::tree::objectpath::Tree<dbus::tree::methodtype::MTSync, ()>
```

I forgot to mention this above, but I'm already using `MTSync`. Should that mean that `start_receive` should just work? It worked in 0.7.1.

**Comment by nikonthethird** [comment]
I produced a minimal example. This code compiles when using `dbus` version `0.7.1`, but fails with the above error message on `0.8.1`:

```rust
fn get_connection() -> dbus::blocking::Connection {
    unimplemented!()
}

fn get_tree() -> dbus::tree::Tree<dbus::tree::MTSync<()>, ()> {
    unimplemented!()
}

fn main() {
    let connection = get_connection();
    let tree = get_tree();
    
    tree.start_receive(&connection);
}
```

**Comment by diwic** [comment]
@nikonthethird Ah, so it worked in 0.7.1? Then I should be able to bisect it. 

What I meant with the added commit was that if you change `start_receive` to `start_receive_send` then it should work.

**Comment by nikonthethird** [comment]
Oh, I totally missed that, sorry.

Yeah, after pointing Cargo to Github and using `start_receive_send`, it's now working. That fixed it.

But I guess I'll stick to `0.7.1` for now until you come to a decision after bisecting ;) But FYI, after that last change my application builds and works again. Yay!

**Comment by diwic** [comment]
Offending commit:

    commit 8620a96fcdb6fd4ee1e38bd2577ffd5cfeff8052 (refs/bisect/bad)
    Author: David Henningsson <diwic@ubuntu.com>
    Date:   Thu Oct 10 20:06:32 2019 +0200
     
        Blocking: Split Connection -> LocalConnection, add Send Connection

Okay, so what happened in this commit is that the existing `Connection` (which was neither `Send` nor `Sync`) got renamed to `LocalConnection`, and a new `Connection` was created which is `Send` but not `Sync`. The reason was to be more consistent with naming used in other crates.

Unfortunately this was something I failed to document properly. But in essence, either rename your `Connection` to `LocalConnection` or change `start_receive` to `start_receive_send`.

**Comment by nikonthethird** [comment]
I changed all instances of `dbus::blocking::Connection` to `dbus::blocking::LocalConnection` and that was everything I had to do. Thank you!
