### ISSUE TITLE
Accessing Connection within tree method handler

### ISSUE THREAD

**Issue by skystrife** [diwic/dbus-rs#232]
I'm trying to implement a method handler that needs to issue more queries to DBus within the method handler in order to produce the appropriate response.

Essentially, the method handler is being invoked with a message that has an argument that indicates a path on the session bus. I want to invoke a "NameHasOwner" method on the DBus interface to validate that the path is valid and does actually have the interface I expect on that path, and return `true` if it's valid and `false` if not. My issue is that I have no reference to the underlying `Connection` within the method handler to use to make that query.

Is there a way to get at the underlying `Connection` struct within a method handler, like we can from a signal handler? (`match_signal` on a `Proxy` has the `Connection` as the second argument to the callback.)

This is difficult (impossible?) to do manually (I was trying to have an `Arc<Mutex<Connection>>` or an `Rc<RefCell<Conection>>` and move a clone into the method handler, but we need a mutable reference to invoke `conn.process(...)`, which makes getting even an immutable reference within the method handler impossible since there will be an outstanding mutable borrow until `process(...)` returns.

This might just be me being unfamiliar with Rust, but it feels like my life would be a whole lot easier if I could have a `&Connection` passed to the method handler. Is there some workaround that I can use instead?

**Comment by diwic** [comment]
Thanks for your bug report. I don't have a great fix for your problem but I can think of two workarounds:

 * Use two connections. This is likely the easiest quick fix.
 * Use the `MatchingReceiver` trait directly to set up a separate method handler: 
   * Start with `MatchRule::new_method_call()` and add matches for `path`, `interface` and `member`.
   * Call `MatchingReceiver::start_receive`. 
   * Your callback will have to parse the incoming message and also send the reply (with `msg.method_return()`).
   * You can still add the method handler in the `tree` to aid introspection. Add the tree *after* you add your separate method handler, so that the right handler will be called.
