### ISSUE TITLE
Does SyncConnection have a way to register object paths?

### ISSUE THREAD

**Issue by jbaublitz** [diwic/dbus-rs#290]
I have been looking through the API for `SyncConnection` in 0.8.4 and there's one thing I still can't wrap my head around. The low level FFI `Connection` allows you to register object paths on the connection, but it appears that `SyncConnection` does not. Is there a way around this?

**Comment by diwic** [comment]
First; the most common scenario is to use `dbus-crossroads` (new and shiny) or `dbus-tree` (legacy) crates to handle all of that for you.
Second; it depends on what you mean with "register". `ffidisp::Connection` uses the builtin functionality in the C library to dispatch incoming method calls, the newer `SyncConnection` does not do that (for better performance and fault tolerance). In that C library there is a builtin small introspection capability that just answers to which object paths there are. If that is what you mean with "register", then I recommend using `dbus-crossroads`, because it does such introspection by default.

If you just need a callback when there is an incoming method call on a specific object path, `SyncConnection` implements the  `MatchingReceiver` trait. So call  `MatchRule::new_method_call()`, set the matchrule's path, then call `MatchingReceiver::start_receive` on the `SyncConnection`.

**Comment by jbaublitz** [comment]
While I hope to eventually try out `dbus-crossroads`, I'm focused more on two other matters for the time being. Just to give you a little bit more background, I'm looking to improve our use of D-Bus in two ways:
1. I want the connection object to be `Send + Sync` so I've switched from `ffidisp::Connection` to `SyncConnection`.
2. I want to have the higher level API handle our requests at a bit higher of a level than the file descriptor level for D-Bus connections. The `Tree`/`SyncConnection` API seems like it can do that for us.

I have successfully made changes so that our tree and connection objects are `Send + Sync`, but I'm mostly worried about whether the way we define D-Bus methods will translate over to the `SyncConnection` API.

For setup, we:
1. Create a `Tree`.
2. Register it with an `ffidisp::Connection`.
3. Handle incoming method calls from `ffidisp::Connection` using the `Tree::handle()` method manually.

Currently we do the following when we create a D-Bus object:
1. Use a `Factory` to construct our interfaces/method calls.
2. Insert the object path into the tree.
3. Register the object path with `ffidisp::Connection` using the method `.register_object_path()`.

If I'm understanding you correctly, with `SyncConnection`, this would translate more into:
1. Use a `Factory` to construct our interface/method calls.
2. Insert the object path into the tree.
3. Create a match rule to dispatch specific object paths to their destination handler in the `Tree`?

What I was currently considering was using the `Factory` as described above, building the `Tree` as described above, and then running `Tree::start_receive_sync()` in a loop with the `SyncConnection`. Would the D-Bus server be aware of what object paths are available if I did this? If so, what would actually make the D-Bus paths visible if we're no longer calling `ffidisp::Connection::register_object_path()`? If not, is this what the match rules would help with? If I do need to set match rules, how would I then dispatch that to the defined handlers in `Tree`? I'm not really sure how all of these pieces fit together.

**Comment by diwic** [comment]
> Would the D-Bus server be aware of what object paths are available if I did this?

The D-Bus daemon is not aware about "available" object paths. Method calls are forwarded from one client to another without filtering. 

When you use debugging tools (such as D-feet), it calls introspection methods on the client to give a hint of what object paths are available. For `crossroads`, this is handled by default. For `Tree`, you need to add the root path `/`, like in [this example](https://github.com/diwic/dbus-rs/blob/master/dbus-tree/examples/server.rs#L62), and it will be handled as well. I recommend looking at this example because it looks a lot like what you're trying to do (except it's a `LocalConnection` instead of a `SyncConnection`).

So your setup would then be:

 * Use a Factory to construct our interface/method calls.
 * Insert the object path into the tree
 * Insert the introspectable root path into the tree (as in the example)
 * Call `Tree::start_receive_sync`
 * Call `SyncConnection::process` in a loop

**Comment by jbaublitz** [comment]
Okay, I think I understand a little bit better now what you're referring to. The object path being "registered" with the connection as referenced here in the `Tree::add()` and `Tree::insert()` methods:

```
Note: This does not register a path with the connection, so if the tree is currently registered, you might want to call Connection::register_object_path to add the path manually.
```

is only referring to `ffidisp::Connection` and that is only due to the fact that that particular connection handle uses introspection where structs like `SyncConnection` do not so it is only necessary to use the `Tree` struct for handling in that case. Is this correct?

**Comment by diwic** [comment]
> Note: This does not register a path with the connection, so if the tree is currently registered, you might want to call Connection::register_object_path to add the path manually.

This comment is only relevant for `ffidisp::Connection` which I hope most people have moved away from by now. I'll remove the comment.

 > use the Tree struct for handling in that case.

The Tree struct handles introspection for the root path `/` if you add it (as indicated by the previous comment). In practice, this provides the same functionality as registering object paths on a `ffidisp::Connection`.

**Comment by jbaublitz** [comment]
That comment in the documentation really was the confusing part for me. Thanks for the help!
