### ISSUE TITLE
If multiple match rules match a message, it only gets sent to the first one

### ISSUE THREAD

**Issue by qwandor** [diwic/dbus-rs#346]
If I call ` dbus::nonblock::SyncConnection::add_match` two or more times, either with the same `MatchRule` or with `MatchRule`s which match some of the same messages, and then there is a message which both of them match, I would expect both callbacks or message streams to get the message. Instead, only the first one gets it.

It looks like the bug is in `Process::process_one`, which only ever sends the message to one callback. I don't understand why it needs to remove the matching filter (with `remove_matching`) and then add it back in after calling the callback, but in any case it should be doing this for all matching filters rather than just the first one.

**Comment by qwandor** [comment]
I've had a look at fixing this, but the problem is that `Message` doesn't implement `Clone`.

**Comment by diwic** [comment]
This is by design, not a bug. 

It seems very counter intuitive do match more than one for a method call message (there will be two replies back to the caller?!). For a signal message, I guess there could be use cases for both behaviors, but I would have expected a user to have done something like match the message once, process it and then send it to the relevant places of its own, but I guess it could be helpful to have that been done in the dbus crate somehow. It should not be the default behavior though.

**Comment by diwic** [comment]
To answer quickly on the Clone question; if you want to clone a Message you should probably put it inside an `Arc` or `Rc`. As you noted, `dbus_message_copy` changes the copy to reset the serial, which is not okay (and it's probably slower, too). And using `dbus_message_ref` would make Message non-Send, so that is not an option either.

**Comment by diwic** [comment]
> I don't understand why it needs to remove the matching filter (with remove_matching) and then add it back in after calling the callback

I want to avoid holding locks while calling callbacks, primarily a callback should be free to modify the chain of filters, e g by adding and removing other matches. Holding a lock would make that cause a deadlock.

**Comment by diwic** [comment]
Okay, so given some additional thought, I think what could make sense is to add a function on the `Connection` (and `LocalConnection` / `SyncConnection` ) that would activate a "copy signal messages mode" that would send copies of the message into the callbacks instead of the original message. It still annoys me that this will be less optimal than just wrapping the message inside an `Arc` though, so I'm not sure about this either. Maybe it's better just to say to the user that this is the way it works and they'll have to provide their own dispatching on top?

**Comment by qwandor** [comment]
Ah, I didn't realise that `add_match` could also be used for method call messages, I don't see a usecase for having multiple matches for those. My interest is in signal messages, where I was very surprised to find that if there happen to be multiple matches for a message only one of them will get it. This is not documented anywhere that I could see, and resulted in a serious bug in my library built on top of this. Having a match registered in one part of the program break a match registered in another part breaks encapsulation and results in confusing bugs.

Wrapping the message in an `Arc` would work for me, but it's a significant change to the API so I was worried that it might break other users of the library.

> I want to avoid holding locks while calling callbacks, primarily a callback should be free to modify the chain of filters, e g by adding and removing other matches. Holding a lock would make that cause a deadlock.
What happens if another match message comes in while the callback is still running? Is it just ignored? That seems wrong too.

Having to activate a special mode for signal messages to work properly would also be fine for my case, but seems likely to be confusing to new users. Maybe it should be the default? When would they not want to activate this mode?

**Comment by diwic** [comment]
> This is not documented anywhere that I could see

Noted, better documentation would not hurt.

 > What happens if another match message comes in while the callback is still running?

The next message will not be processed until the callback is put back; this is true for both `blocking` and `nonblock`.

 > Having to activate a special mode for signal messages to work properly would also be fine for my case, but seems likely to be confusing to new users. Maybe it should be the default? When would they not want to activate this mode?

When they don't want to pay an additional performance tax (in the form of `dbus_message_copy`) for supporting a use case not relevant to them. And when they are interested in the serial (although I'm not sure if they will ever be). 

Additionally, one could argue that treating signal and method call messages different by default would also be confusing to new users.

**Comment by qwandor** [comment]
I've just realised this requires some more plumbing in `dbus-tokio` to be able to actually enable the fixed signal match mode. Taking a look now.
