### ISSUE TITLE
Feature request: Support single threaded designs with dbus-crossroads

### ISSUE THREAD

**Issue by Allen-Webb** [diwic/dbus-rs#349]
Currently, dbus-crossroads has the Send trait sprinkled throughout the API. If possible use ?Send so that singled threaded server implementations do not need to use Arc+Mutex.

**Comment by Allen-Webb** [comment]
Nevermind. It looks like ?Sized is valid but ?Send is not.

**Comment by diwic** [comment]
I considered this when making dbus-crossroads, but there is just no good enough solution in the Rust language for this. 

One could make things generic over `Send` and `Sync` like dbus-tree does, but the code required to maintain that is just too much of a burden. IIRC, I even tried it but gave up because the code ended up being too hairy.

If someone wants to implement this, let me know. But be warned, it's not for the faint of heart.

**Comment by diwic** [comment]
Closing due to lack of interest/activity.

**Comment by Allen-Webb** [comment]
I might come back to this to take a shot at it if performance justifies it, but I am fine with it being closed for now.
