### ISSUE TITLE
[update future version] warning when packaging

### ISSUE THREAD

**Issue by 51yu** [diwic/dbus-rs#368]
```
warning: package `futures-channel v0.3.18` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
warning: package `futures-core v0.3.18` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
warning: package `futures-task v0.3.18` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
warning: package `futures-util v0.3.18` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
```
when package my app depends on dbus, I found ^^, seems like `future` version is out of date

**Comment by mulkieran** [comment]
Try running cargo-update in your app's development directory. I don't see any evidence that dbus-rs is pinning these dependencies.

**Comment by 51yu** [comment]
not sure, I may be wrong see [link](https://github.com/diwic/dbus-rs/blob/master/dbus/Cargo.toml#L19)

**Comment by mulkieran** [comment]
@51yu The way version specifications work in cargo means that that specification indicates a range of appropriate versions that are acceptable to the D-Bus library. It is your app's current setup that determines what versions your app is dependent on. It turns out that the app I work on, stratisd, is also currently dependent on futures-channel v0.3.18[1] via its dependency on dbus-rs. However, I just ran cargo-update in stratisd's top directory, and now it depends on futures-channel v0.3.17 instead as I can tell by looking at the output of cargo-tree. From that evidence, I can infer that futures-channel has no version more recent than 0.3.18 that has not been yanked and I can confirm this via crates.io[2].

This is really not an issue for dbus-rs at all, and you should be able to manage it entirely on your side.

You can find out more about the version specification in the Cargo manual.

[1] https://github.com/stratis-storage/stratisd/blob/master/Cargo.lock#L353
[2] https://crates.io/crates/futures-channel/versions

**Comment by diwic** [comment]
I agree with @mulkieran, this is not a bug in dbus-rs.
