### ISSUE TITLE
Is it possible to return Dict in a dbus-crossroads interface property

### ISSUE THREAD

**Issue by Sinono3** [diwic/dbus-rs#371]
The current approach is to use a HashMap, but doing that, the ordering of the items is not retained. This is the error I get when returning a Dict:

```
error[E0277]: `*mut c_void` cannot be shared between threads safely
   --> src/platform/linux/mod.rs:222:32
    |
222 |         b.property("Metadata").get({
    |                                ^^^ `*mut c_void` cannot be shared between threads safely
    |
    = help: within `Message`, the trait `Sync` is not implemented for `*mut c_void`
    = note: required because it appears within the type `Message`
    = note: required because of the requirements on the impl of `Send` for `&Message`
    = note: required because it appears within the type `(&Message, *const &str, *const &str)`
    = note: required because it appears within the type `PhantomData<(&Message, *const &str, *const &str)>`
    = note: required because it appears within the type `dbus::arg::Dict<'_, &str, &str, std::array::IntoIter<(&str, &str), 3_usize>>`
```

Is there a way to circumvent this? Happy new year!

**Comment by diwic** [comment]
Hi!

It seems like the answer currently is "no". Maybe this can change, but:

The D-Bus spec does not say anything about a array of dict entries being unordered or ordered, but it is "common understanding" of dictionaries are that they are unordered. [example](https://computersciencewiki.org/index.php/Dictionaries) 

If ordering is needed I would use an array of structs instead of a dictionary. Is that possible for you?

**Comment by diwic** [comment]
Perhaps the easiest fix is to implement dicts for `BTreeMap` as well, just as we do for Hashmaps?
