### ISSUE TITLE
Move to being a pure Rust library?

### ISSUE THREAD

**Issue by jansol** [diwic/dbus-rs#60]
Cutting external dependencies is always nice and it looks like there is a pure Rust DBus implementation [here](https://github.com/srwalter/dbus-bytestream) and a useful looking utility lib [here](https://github.com/srwalter/dbus-serialize). Any reason to not make use of them?

**Comment by diwic** [comment]
From a quick glance, both of them seem far too immature to replace what the C library I'm linking to does. I didn't look thoroughly, so take this with a grain of salt, but...

The first one can barely get the body out of the message, [see here](https://docs.rs/dbus-bytestream/0.1.3/dbus_bytestream/message/struct.Message.html) - `Value` is not even public. The library probably has potential, but not now.

The second one does not do much - it only adds some serialize/deserialize, which in turn depends on its own enum types. I used enums at first put after a while switched to generics due to increased ergonomics and performance.

**Comment by jansol** [comment]
Fair enough. I'll leave it to you to close this or leave it open as a tracking issue.
