### ISSUE TITLE
Puzzled about how to emit PropertiesChanged signal for a RO property

### ISSUE THREAD

**Issue by mulkieran** [diwic/dbus-rs#66]
Hi!

We have a bunch of properties that are RO by intention (can not be set via the D-Bus interface).
But the value of a RO property may still change. This change could result from side-effects from other procedure calls or any number of reasons.

When this happens, it is still desirable to emit a PropertiesChanged signal which includes the information about the property changed in a reasonably timely manner. We're not sure if we want to just invalidate or actually give the new value.

Are there currently recommended ways to go about doing this, i.e., emitting a PropertiesChanged signal with information for a RO property?

**Comment by diwic** [comment]
Hmm...I thought I have considered this, but the closest thing you can call today is "set_as_variant" (which returns the signal, if set), but that requires you to have a `&mut Iter`, which you don't have.

So I'll keep this one open for the time being, noticing that you don't get any help to generate the "emits changed" signal the way you probably could.

**Comment by diwic** [comment]
@mulkieran Hi! I have not forgot your issue, not sure if you have or not. :-)

Anyhow, I implemented signals in my code generator and added the result to the [stdintf module](https://github.com/diwic/dbus-rs/blob/master/dbus/src/stdintf.rs), which includes the `PropertiesChanged` signal.

With that struct (with the name `OrgFreedesktopDBusPropertiesPropertiesChanged`, kinda longish :-) ) you can easily send/receive that signal (see e g `SignalArgs::to_emit_message`). That gives some help compared to the current situation but one problem remains: how to get from a `tree::Property` to a `OrgFreedesktopDBusPropertiesPropertiesChanged` struct easily.

Now, `tree::Property` works with low-level `Iter` and `IterAppend` stuff in its `on_get` / `on_set` handlers, which is a bit incompatible with the struct, which works with Rust datatypes (and `Box<RefArg>` when necessary).

This basically leaves me a few options:

 * Revamp `tree::Property` to work with `RefArg` rather than `Iter` and `IterAppend`. This has the potential benefit of removing a footgun (you can now append, e g, two properties in your handler instead of one and get a broken message as a result), but the downside is broken backwards compatibility for `on_get` / `on_set` handlers. 
 * Allow the property to hand out a PropertiesChanged struct, but only for `where D::Property: RefArg`. Can be seen as a lightweight version of option 1 that keeps backwards compatibility. I suspect this will not work for stratis, where (I think?) you dynamically look up the right property instead of storing it in-tree.
 * I'll skip using `stdintf::OrgFreedesktopDBusPropertiesPropertiesChanged` and make a `tree::PropertiesChanged(Arc<tree::Property>)` struct, which implements the `SignalArgs` interface. We now have two different `PropertiesChanged` structs...

**Comment by diwic** [comment]
@mulkieran Okay, so I went for a version of the second bullet point above that I think will work for you as well; because you then need to supply the new value in a closure. 

Give it a shot and please reopen if the docs are confusing or if it does not work according to your expectations. Thanks!
