### ISSUE TITLE
Own Error types

### ISSUE THREAD

**Issue by manuels** [diwic/dbus-rs#95]
I am using error-chain for my rust projects. In conjunction with dbus-rs I run into the problem, that most (all?) dbus-rs methods return a `Result<..., String>` or `Result<..., &'static str>` which are not usable with error-chain.

Would it be possible to make the error-types implement `std::error::Error`? That would make life much easier!

**Comment by diwic** [comment]
I'm not very familiar with error-chain, but since `String` and `&str` both can be converted to `Box<Error>` easily [see here](https://doc.rust-lang.org/src/std/error.rs.html#177), maybe this is something that can be fixed in error-chain?

Also, I think many dbus-rs methods returns a `dbus::error` (which does implement `std::error::Error`)?

Could you clarify/elaborate?

**Comment by diwic** [comment]
Oops, closed by mistake

**Comment by manuels** [comment]
I think, you are right, @diwic:

            let msg = Message::new_method_call(DBUS_DEST, DBUS_OBJ_PATH, DBUS_IFACE, "Get")
                .map_err(Error::from).chain_err(|| "Failed to create D-Bus message")?;

Works fine. This should probably be fixed in error_chain!
